theme: jekyll-theme-minimal

title: Charles Thomas

name: Charles Thomas

description: Software Engineer currently trying to fix payroll at https://hyko.uk Also studying Maths & Philosophy at Durham (Formerly at Monzo)
